from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

HEADER = """# References\n\n> Generated from [`references/sources.json`](references/sources.json). Do not edit this file manually; run `cyber-library-references render`.\n\nCyber Library keeps external platform, catalog, identifier, authority, deployment and prior-art references explicit. These references document upstream interfaces and design evidence; they do not transfer third-party licenses to Cyber Library source code.\n"""


def load_sources(root: str | Path = ".") -> list[dict[str, str]]:
    root = Path(root).resolve()
    path = root / "references" / "sources.json"
    raw = json.loads(path.read_text(encoding="utf-8"))
    sources = raw.get("sources") if isinstance(raw, dict) else None
    if not isinstance(sources, list):
        raise ValueError("references/sources.json must contain a sources array")
    return sources


def validate_sources(sources: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    ids: set[str] = set()
    urls: set[str] = set()
    for index, source in enumerate(sources):
        if not isinstance(source, dict):
            errors.append(f"sources[{index}] must be an object")
            continue
        for key in ("id", "name", "kind", "url", "purpose"):
            if not str(source.get(key) or "").strip():
                errors.append(f"sources[{index}].{key} is required")
        sid = str(source.get("id") or "")
        url = str(source.get("url") or "")
        if sid:
            if sid in ids:
                errors.append(f"duplicate source id: {sid}")
            ids.add(sid)
        if url:
            if not url.startswith("https://"):
                errors.append(f"source URL must use https: {url}")
            if url in urls:
                errors.append(f"duplicate source URL: {url}")
            urls.add(url)
    return errors


def render_references(sources: list[dict[str, str]]) -> str:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for source in sources:
        groups[str(source["kind"])].append(source)
    lines = [HEADER.rstrip(), ""]
    for kind in sorted(groups):
        title = kind.replace("-", " ").title()
        lines.extend([f"## {title}", ""])
        for source in sorted(groups[kind], key=lambda item: item["name"].casefold()):
            lines.append(f"- **[{source['name']}]({source['url']})** — {source['purpose']}  ")
            lines.append(f"  Reference ID: `{source['id']}`")
        lines.append("")
    lines.extend([
        "## Repository Citation",
        "",
        "For citing Cyber Library itself, use [`CITATION.cff`](CITATION.cff). GitHub renders that file through the repository's **Cite this repository** interface.",
        "",
    ])
    return "\n".join(lines)


def check_references(root: str | Path = ".") -> dict[str, Any]:
    root = Path(root).resolve()
    try:
        sources = load_sources(root)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        return {"ok": False, "errors": [str(exc)], "sources": 0, "markdown_matches": False}
    errors = validate_sources(sources)
    expected = render_references(sources)
    path = root / "REFERENCES.md"
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    matches = actual == expected
    if not matches:
        errors.append("REFERENCES.md is out of sync with references/sources.json")
    return {"ok": not errors, "errors": errors, "sources": len(sources), "markdown_matches": matches}


def write_references(root: str | Path = ".") -> dict[str, Any]:
    root = Path(root).resolve()
    sources = load_sources(root)
    errors = validate_sources(sources)
    if errors:
        raise ValueError("; ".join(errors))
    path = root / "REFERENCES.md"
    content = render_references(sources)
    changed = not path.exists() or path.read_text(encoding="utf-8") != content
    path.write_text(content, encoding="utf-8")
    return {"ok": True, "sources": len(sources), "path": "REFERENCES.md", "changed": changed}


def main() -> int:
    parser = argparse.ArgumentParser(prog="cyber-library-references", description="Validate or render the repository reference index.")
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("check", "render"):
        cmd = sub.add_parser(name)
        cmd.add_argument("--root", default=".")
    args = parser.parse_args()
    if args.command == "render":
        try:
            result = write_references(args.root)
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            print(json.dumps({"ok": False, "errors": [str(exc)]}, ensure_ascii=False, indent=2))
            return 2
    else:
        result = check_references(args.root)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result.get("ok") else 2


if __name__ == "__main__":
    raise SystemExit(main())
