const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const api=async(url,opt={})=>{const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||d.error||`HTTP ${r.status}`);return d};
const clear=e=>{while(e.firstChild)e.removeChild(e.firstChild)},txt=(e,v,f='—')=>e.textContent=v||f;
function list(e,a,empty='暂无'){clear(e);for(const v of a?.length?a:[empty]){const li=document.createElement('li');li.textContent=v;if(v===empty)li.className='muted';e.append(li)}}
function tags(e,a,cls=''){for(const v of a||[]){const s=document.createElement('span');s.className=`tag ${cls}`;s.textContent=v;e.append(s)}}
const isbnOf=r=>(r?.edition?.identifiers?.isbn13||r?.edition?.identifiers?.isbn10||[])[0]||null;
const isbnLike=v=>[10,13].includes(v.replace(/[^0-9Xx]/g,'').length);
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${b.dataset.tab}`));if(b.dataset.tab==='universe'&&!U.loaded)loadUniverse()});
(async()=>{try{const s=await api('/api/stats'),c=$$('#stats strong');c[0].textContent=s.works??'—';c[1].textContent=s.editions??'—';c[2].textContent=s.llm_enabled?'ON':'LOCAL'}catch{}try{const {categories}=await api('/api/categories');for(const sel of [$('#category'),$('#universe-category')])for(const n of categories||[])if(n!=='Unclassified'){const o=document.createElement('option');o.value=o.textContent=n;sel.append(o)}}catch{}})();
function mind(node,root){clear(root);const build=n=>{const d=document.createElement('div');d.className='mind-node';const l=document.createElement('div');l.className='mind-label';l.textContent=n.name||'—';d.append(l);if(n.children?.length){const c=document.createElement('div');c.className='mind-children';n.children.forEach(x=>c.append(build(x)));d.append(c)}return d};if(node)root.append(build(node));else root.textContent='暂无思维导图'}
function chapters(a){const e=$('#chapter-summaries');clear(e);if(!a?.length){e.textContent='暂无可靠章节摘要';return}for(const x of a){const d=document.createElement('div');d.className='chapter';const h=document.createElement('strong');h.textContent=x.title||'Section';const p=document.createElement('p');p.textContent=x.summary||'';d.append(h,p);e.append(d)}}
function render(r){$('#book').classList.remove('hidden');const w=r.work||{},e=r.edition||{},a=r.analysis||{};txt($('#analysis-level'),a.level,'L0');txt($('#edition-id'),e.id,'');txt($('#book-title'),w.title||e.title,'Untitled');txt($('#authors'),(w.authors||[]).join(' / '),'作者未知');txt($('#brief'),a.brief,'证据不足');txt($('#summary'),a.summary,'证据不足');txt($('#detailed'),a.detailed,'现有证据不足，未生成超出来源范围的详细解读。');const c=$('#cover');if(e.cover_url){c.src=e.cover_url;c.hidden=false;c.onerror=()=>c.hidden=true}else c.hidden=true;clear($('#facts'));for(const [k,v] of [['Language',e.language],['Publisher',(e.publishers||[]).join(' / ')],['Published',e.publish_date],['Pages',e.page_count],['Format',e.physical_format],['ISBN',isbnOf(r)]])if(v){const s=document.createElement('span');s.className='fact';s.textContent=`${k}: ${v}`;$('#facts').append(s)}clear($('#tags'));tags($('#tags'),a.categories||w.categories,'category');tags($('#tags'),(a.tags||w.subjects||[]).slice(0,24));list($('#themes'),a.themes||[],'暂无可靠主题');list($('#key-points'),a.key_points||[],'暂无可靠关键点');list($('#toc'),a.table_of_contents?.length?a.table_of_contents:(a.outline||[]),'暂无目录/大纲');chapters(a.chapter_summaries);mind(a.mindmap,$('#mindmap'));clear($('#sources'));for(const p of r.provenance||[]){const li=document.createElement('li');li.textContent=[p.source,p.source_id,p.license].filter(Boolean).join(' · ');$('#sources').append(li)}for(const s of a.sources||[]){const li=document.createElement('li');li.textContent=s;$('#sources').append(li)}list($('#warnings'),a.warnings||[],'无额外警告');const isbn=isbnOf(r);isbn?loadGraph(isbn):drawGraph({nodes:[],edges:[]});$('#book').scrollIntoView({behavior:'smooth',block:'start'})}
async function resolve(isbn){$('#search-status').textContent=`正在解析 ${isbn}…`;try{const r=await api(`/api/resolve?isbn=${encodeURIComponent(isbn)}&analysis=auto`);clear($('#search-results'));render(r);$('#search-status').textContent=`解析完成 · ${r.analysis?.level||'L0'}`;return true}catch(e){$('#search-status').textContent=`解析失败：${e.message}`;return false}}
function results(a){const e=$('#search-results');clear(e);if(!a.length){e.textContent='没有找到结果。';return}for(const x of a){const d=document.createElement('article');d.className='result-card';const im=document.createElement('img');im.className='result-cover';if(x.cover_url)im.src=x.cover_url;const b=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p'),m=document.createElement('p');h.textContent=x.title||'Untitled';p.textContent=(x.authors||[]).join(' / ')||'作者未知';m.textContent=[x.publish_date,...(x.categories||[]).slice(0,2)].filter(Boolean).join(' · ');b.append(h,p,m);d.append(im,b);if(x.isbn)d.onclick=()=>resolve(x.isbn);e.append(d)}}
$('#search-form').onsubmit=async ev=>{ev.preventDefault();const q=$('#query').value.trim();if(!q)return;if(isbnLike(q)&&await resolve(q))return;$('#search-status').textContent='正在检索…';const p=new URLSearchParams({q,limit:'24'});if($('#category').value)p.set('category',$('#category').value);try{const d=await api(`/api/search?${p}`);results(d.results||[]);$('#search-status').textContent=`找到 ${(d.results||[]).length} 条结果。`}catch(e){$('#search-status').textContent=`检索失败：${e.message}`}};
function canvas(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);return{ctx:c.getContext('2d'),w:c.width,h:c.height,d}}
let graph=null;async function loadGraph(isbn){try{graph=await api(`/api/graph?isbn=${encodeURIComponent(isbn)}`);drawGraph(graph);$('#graph-status').textContent=`${graph.nodes.length} nodes · ${graph.edges.length} edges`}catch(e){$('#graph-status').textContent=`图谱不可用：${e.message}`}}
function color(k){return({work:'#79a8ff',author:'#70d5b5',subject:'#a889ff',category:'#ffbf77',publisher:'#79d0ed',year:'#d4dfef',related_work:'#ff8897'})[k]||'#a9b8c9'}
function drawGraph(g){const c=$('#graph-canvas'),{ctx,w,h,d}=canvas(c);ctx.clearRect(0,0,w,h);if(!g?.nodes?.length)return;const pos=new Map([[g.root,{x:w/2,y:h/2}]]),rest=g.nodes.filter(n=>n.id!==g.root);rest.forEach((n,i)=>{const a=2*Math.PI*i/rest.length,r=.4*Math.min(w,h);pos.set(n.id,{x:w/2+Math.cos(a)*r,y:h/2+Math.sin(a)*r})});ctx.strokeStyle='#314054';for(const e of g.edges||[]){const a=pos.get(e.source),b=pos.get(e.target);if(a&&b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}for(const n of g.nodes){const p=pos.get(n.id);if(!p)continue;ctx.fillStyle=color(n.kind);ctx.beginPath();ctx.arc(p.x,p.y,(n.id===g.root?8:5)*d,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b9c7d8';ctx.font=`${10*d}px system-ui`;ctx.textAlign='center';ctx.fillText((n.label||'').slice(0,24),p.x,p.y+14*d)}}
$('#fulltext-form').onsubmit=async ev=>{ev.preventDefault();const t=$('#fulltext-text').value.trim();if(t.length<100){$('#fulltext-status').textContent='正文至少 100 字符';return}$('#fulltext-status').textContent='分析中…';try{const r=await api('/api/analyze-text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('#fulltext-title').value.trim()||undefined,isbn:$('#fulltext-isbn').value.trim()||undefined,rights:$('#fulltext-rights').value,text:t})});$('#fulltext-status').textContent='完成';$('[data-tab="explore"]').click();render(r)}catch(e){$('#fulltext-status').textContent=`失败：${e.message}`}};
const U={loaded:false,points:[],tiles:[],mode:'points',cx:.5,cy:.5,zoom:1,drag:false,last:null,timer:null},uc=$('#universe-canvas');
function bounds(){const h=.5/U.zoom;return{minX:Math.max(0,U.cx-h),maxX:Math.min(1,U.cx+h),minY:Math.max(0,U.cy-h),maxY:Math.min(1,U.cy+h)}}
function drawU(){const {ctx,w,h,d}=canvas(uc),b=bounds();ctx.fillStyle='#05070a';ctx.fillRect(0,0,w,h);if(U.mode==='tiles'&&U.tiles.length){const maxCount=Math.max(1,...U.tiles.map(x=>x.count||0));for(const t of U.tiles){const x0=(t.x-t.size/2-b.minX)/(b.maxX-b.minX)*w,y0=(t.y-t.size/2-b.minY)/(b.maxY-b.minY)*h,tw=t.size/(b.maxX-b.minX)*w,th=t.size/(b.maxY-b.minY)*h;if(x0+tw<0||y0+th<0||x0>w||y0>h)continue;const a=.12+.76*Math.log1p(t.count||0)/Math.log1p(maxCount);ctx.fillStyle=`rgba(121,168,255,${a.toFixed(3)})`;ctx.fillRect(x0,y0,Math.max(1,tw),Math.max(1,th))}const total=U.tiles.reduce((n,x)=>n+(x.count||0),0);$('#universe-count').textContent=`${total.toLocaleString()} editions · ${U.tiles.length} cells · zoom ${U.zoom.toFixed(1)}×`}else{for(const p of U.points){if(p.x<b.minX||p.x>b.maxX||p.y<b.minY||p.y>b.maxY)continue;const x=(p.x-b.minX)/(b.maxX-b.minX)*w,y=(p.y-b.minY)/(b.maxY-b.minY)*h;ctx.fillStyle='#79a8ff';ctx.fillRect(x-1.5*d,y-1.5*d,3*d,3*d)}$('#universe-count').textContent=`${U.points.length} points · zoom ${U.zoom.toFixed(1)}×`}}
async function loadUniverse(){U.loaded=true;const b=bounds(),z=Math.max(0,Math.floor(Math.log2(U.zoom))),p=new URLSearchParams({limit:'5000',min_x:b.minX,max_x:b.maxX,min_y:b.minY,max_y:b.maxY,z:String(z)}),q=$('#universe-query').value.trim(),cat=$('#universe-category').value;if(q)p.set('q',q);if(cat)p.set('category',cat);try{const d=await api(`/api/universe?${p}`);U.mode=d.mode||'points';U.points=d.points||[];U.tiles=d.tiles||[];drawU()}catch(e){$('#universe-count').textContent=`失败：${e.message}`}}
const schedule=()=>{clearTimeout(U.timer);U.timer=setTimeout(loadUniverse,180)};$('#universe-refresh').onclick=loadUniverse;$('#universe-reset').onclick=()=>{U.cx=U.cy=.5;U.zoom=1;loadUniverse()};uc.onwheel=e=>{e.preventDefault();U.zoom=Math.max(1,Math.min(512,U.zoom*(e.deltaY<0?1.35:1/1.35)));drawU();schedule()};uc.onpointerdown=e=>{U.drag=true;U.last={x:e.clientX,y:e.clientY};uc.setPointerCapture(e.pointerId)};uc.onpointermove=e=>{if(!U.drag)return;const r=uc.getBoundingClientRect(),h=.5/U.zoom;U.cx=Math.max(h,Math.min(1-h,U.cx-(e.clientX-U.last.x)/r.width/U.zoom));U.cy=Math.max(h,Math.min(1-h,U.cy-(e.clientY-U.last.y)/r.height/U.zoom));U.last={x:e.clientX,y:e.clientY};drawU()};uc.onpointerup=()=>{U.drag=false;schedule()};uc.onclick=e=>{const r=uc.getBoundingClientRect(),b=bounds(),wx=b.minX+(e.clientX-r.left)/r.width*(b.maxX-b.minX),wy=b.minY+(e.clientY-r.top)/r.height*(b.maxY-b.minY);if(U.mode==='tiles'){const t=U.tiles.find(x=>Math.abs(wx-x.x)<=x.size/2&&Math.abs(wy-x.y)<=x.size/2);if(t){U.cx=t.x;U.cy=t.y;U.zoom=Math.min(512,Math.max(U.zoom*2,2**(t.zoom+1)));loadUniverse()}return}let best=null,dist=14;for(const p of U.points){const x=(p.x-b.minX)/(b.maxX-b.minX)*r.width,y=(p.y-b.minY)/(b.maxY-b.minY)*r.height,d=Math.hypot(x-(e.clientX-r.left),y-(e.clientY-r.top));if(d<dist){dist=d;best=p}}if(best&&best.isbn){$('[data-tab="explore"]').click();resolve(best.isbn)}};
window.addEventListener('resize',()=>{if(graph)drawGraph(graph);drawU()});
