(()=>{
  const nativeFetch=window.fetch.bind(window);
  const jsonResponse=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8'}});
  let staticCatalog;
  let staticProbe;
  const probe=()=>{
    if(staticProbe)return staticProbe;
    staticProbe=nativeFetch('./site-data/catalog.json',{cache:'no-cache'}).then(async response=>{
      if(!response.ok)return null;
      const data=await response.json();
      staticCatalog=data;
      document.documentElement.dataset.cyberMode='github-static';
      if(!document.querySelector('.static-badge')){const badge=document.createElement('div');badge.className='static-badge';badge.textContent='GitHub-only · no server';document.querySelector('.hero')?.prepend(badge)}
      return data;
    }).catch(()=>null);
    return staticProbe;
  };
  const arr=v=>Array.isArray(v)?v:(v?[v]:[]);
  const isbnOf=r=>[...arr(r?.edition?.identifiers?.isbn13),...arr(r?.edition?.identifiers?.isbn10)][0]||null;
  const norm=v=>String(v||'').toLowerCase().normalize('NFKC');
  const textOf=r=>norm([r?.work?.title,r?.edition?.title,...arr(r?.work?.authors),...arr(r?.work?.subjects),...arr(r?.work?.categories),...arr(r?.edition?.publishers),isbnOf(r)].filter(Boolean).join(' '));
  const publicResult=r=>({edition_id:r.edition?.id,work_id:r.work?.id,title:r.work?.title||r.edition?.title,authors:arr(r.work?.authors),subjects:arr(r.work?.subjects),categories:arr(r.work?.categories),publishers:arr(r.edition?.publishers),language:r.edition?.language,publish_date:r.edition?.publish_date,cover_url:r.edition?.cover_url,isbn:isbnOf(r)});
  const graph=r=>{const w=r.work||{},e=r.edition||{},root=`work:${w.id||e.work_id||e.id}`;const nodes=[{id:root,kind:'work',label:w.title||e.title||'Work'}],edges=[];const add=(kind,label)=>{if(!label)return;const id=`${kind}:${label}`;if(!nodes.some(n=>n.id===id))nodes.push({id,kind,label});edges.push({source:root,target:id,relation:kind})};arr(w.authors).forEach(x=>add('author',x));arr(w.subjects).slice(0,12).forEach(x=>add('subject',x));arr(w.categories).slice(0,6).forEach(x=>add('category',x));arr(e.publishers).slice(0,4).forEach(x=>add('publisher',x));if(e.publish_date)add('year',String(e.publish_date).slice(0,4));return{root,nodes,edges}};
  const knowledge=(records,mode,q)=>{const needle=norm(q);if(mode==='author'){const hits=records.filter(r=>arr(r.work?.authors).some(x=>norm(x).includes(needle))).map(publicResult);return{kind:'author_timeline',query:q,entries:hits.sort((a,b)=>String(a.publish_date||'').localeCompare(String(b.publish_date||'')))}}if(mode==='publisher'){const hits=records.filter(r=>arr(r.edition?.publishers).some(x=>norm(x).includes(needle))).map(publicResult);return{kind:'publisher_view',query:q,editions:hits}}const hits=records.filter(r=>arr(r.work?.subjects).some(x=>norm(x).includes(needle))||arr(r.work?.categories).some(x=>norm(x).includes(needle)));const root=`concept:${q}`;const nodes=[{id:root,kind:'concept',label:q}],edges=[];for(const r of hits){const id=`work:${r.work?.id||r.edition?.id}`;nodes.push({id,kind:'work',label:r.work?.title||r.edition?.title});edges.push({source:root,target:id,relation:'catalog-subject'})}return{kind:'concept_graph',query:q,canonical_query:q,root,nodes,edges,works:hits.map(publicResult)}};
  const localAnalysis=body=>{const text=String(body.text||'').trim(),title=body.title||'Local text';const sentences=text.split(/(?<=[.!?。！？])\s*/).filter(Boolean);const words=text.toLowerCase().match(/[\p{L}\p{N}]{3,}/gu)||[];const stop=new Set(['this','that','with','from','have','were','they','their','there','about','into','以及','一个','我们','他们','可以','这个','这些','进行','通过']);const freq={};for(const w of words){if(!stop.has(w))freq[w]=(freq[w]||0)+1}const tags=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);const headings=text.split('\n').map(x=>x.trim()).filter(x=>/^(#{1,6}\s+|第.{1,12}[章节篇部]|\d+[.、]\s*)/.test(x)).slice(0,40).map(x=>x.replace(/^#{1,6}\s*/,''));return{work:{id:'browser:work',title,authors:[],subjects:tags,categories:['Local Analysis']},edition:{id:'browser:edition',work_id:'browser:work',title,identifiers:body.isbn?{isbn13:[body.isbn]}:{},publishers:[]},analysis:{level:'L3',brief:sentences[0]?.slice(0,220)||'Browser-local analysis.',summary:sentences.slice(0,4).join(' ').slice(0,1200),detailed:sentences.slice(0,12).join(' ').slice(0,4000),tags,categories:['Local Analysis'],themes:tags.slice(0,5),key_points:sentences.slice(0,6),table_of_contents:headings,outline:headings,chapter_summaries:[],mindmap:{name:title,relation:'document',children:tags.slice(0,6).map(name=>({name,relation:'term',children:[]}))},confidence:.55,sources:['browser-local:user-provided'],warnings:['Deterministic browser-local analysis; no text was uploaded to a server.'],model:'browser-local'},provenance:[{source:'Browser local input',source_id:null,url:null,license:body.rights||'user-provided'}]}};
  const route=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href);if(!url.pathname.includes('/api/'))return null;const data=await probe();if(!data)return null;const records=arr(data.records),path=url.pathname.slice(url.pathname.indexOf('/api/'));if(path==='/api/stats')return jsonResponse(data.stats||{});if(path==='/api/categories')return jsonResponse({categories:data.categories||[]});if(path==='/api/search'){const q=norm(url.searchParams.get('q')),category=url.searchParams.get('category');let hits=records.filter(r=>!q||textOf(r).includes(q));if(category)hits=hits.filter(r=>arr(r.work?.categories).includes(category));return jsonResponse({results:hits.slice(0,Number(url.searchParams.get('limit')||24)).map(publicResult),mode:'github-static'})}if(path==='/api/resolve'){const clean=String(url.searchParams.get('isbn')||'').replace(/[^0-9Xx]/g,'').toUpperCase();const found=records.find(r=>[...arr(r.edition?.identifiers?.isbn13),...arr(r.edition?.identifiers?.isbn10)].some(x=>String(x).replace(/[^0-9Xx]/g,'').toUpperCase()===clean));return found?jsonResponse(found):jsonResponse({error:'not_in_static_catalog',detail:'This ISBN is not in the committed GitHub catalog. Add a sourced JSON record under data/catalog/.'},404)}if(path==='/api/graph'){const clean=String(url.searchParams.get('isbn')||'').replace(/[^0-9Xx]/g,'').toUpperCase();const found=records.find(r=>[...arr(r.edition?.identifiers?.isbn13),...arr(r.edition?.identifiers?.isbn10)].some(x=>String(x).replace(/[^0-9Xx]/g,'').toUpperCase()===clean));return found?jsonResponse(graph(found)):jsonResponse({nodes:[],edges:[]})}if(path.startsWith('/api/knowledge/')){const mode=path.split('/').pop(),q=url.searchParams.get(mode==='concept'?'subject':'name')||'';return jsonResponse(knowledge(records,mode,q))}if(path==='/api/universe'){const minX=Number(url.searchParams.get('min_x')||0),maxX=Number(url.searchParams.get('max_x')||1),minY=Number(url.searchParams.get('min_y')||0),maxY=Number(url.searchParams.get('max_y')||1),q=norm(url.searchParams.get('q')),category=url.searchParams.get('category');let hits=records.filter(r=>r.universe&&r.universe.x>=minX&&r.universe.x<=maxX&&r.universe.y>=minY&&r.universe.y<=maxY);if(q)hits=hits.filter(r=>textOf(r).includes(q));if(category)hits=hits.filter(r=>arr(r.work?.categories).includes(category));return jsonResponse({mode:'points',points:hits.map(r=>({...r.universe,isbn:isbnOf(r),title:r.work?.title||r.edition?.title})),tiles:[]})}if(path==='/api/analyze-text'&&String(init.method||'GET').toUpperCase()==='POST'){let body={};try{body=JSON.parse(init.body||'{}')}catch{}return jsonResponse(localAnalysis(body))}return jsonResponse({error:'static_route_missing',detail:path},404)};
  window.fetch=async(input,init={})=>{const response=await route(input,init);return response||nativeFetch(input,init)};
  probe();
})();
